package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * B2bEntities generated by hbm2java
 */
@Entity
@Table(name = "b2b_entities", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"type", "tag0", "tag1", "callid" }))
public class B2bEntities implements java.io.Serializable {

	private Integer id;
	private int type;
	private int state;
	private String ruri;
	private String fromUri;
	private String toUri;
	private String fromDname;
	private String toDname;
	private String tag0;
	private String tag1;
	private String callid;
	private int cseq0;
	private Integer cseq1;
	private String contact0;
	private String contact1;
	private String route0;
	private String route1;
	private String sockinfoSrv;
	private String param;
	private int lm;
	private Integer lrc;
	private Integer lic;
	private Integer legCseq;
	private String legRoute;
	private String legTag;
	private String legContact;
	private String legSockinfo;

	public B2bEntities() {
	}

	public B2bEntities(int type, int state, String fromUri, String toUri,
			String tag0, String callid, int cseq0, String contact0,
			String param, int lm) {
		this.type = type;
		this.state = state;
		this.fromUri = fromUri;
		this.toUri = toUri;
		this.tag0 = tag0;
		this.callid = callid;
		this.cseq0 = cseq0;
		this.contact0 = contact0;
		this.param = param;
		this.lm = lm;
	}

	public B2bEntities(int type, int state, String ruri, String fromUri,
			String toUri, String fromDname, String toDname, String tag0,
			String tag1, String callid, int cseq0, Integer cseq1,
			String contact0, String contact1, String route0, String route1,
			String sockinfoSrv, String param, int lm, Integer lrc, Integer lic,
			Integer legCseq, String legRoute, String legTag, String legContact,
			String legSockinfo) {
		this.type = type;
		this.state = state;
		this.ruri = ruri;
		this.fromUri = fromUri;
		this.toUri = toUri;
		this.fromDname = fromDname;
		this.toDname = toDname;
		this.tag0 = tag0;
		this.tag1 = tag1;
		this.callid = callid;
		this.cseq0 = cseq0;
		this.cseq1 = cseq1;
		this.contact0 = contact0;
		this.contact1 = contact1;
		this.route0 = route0;
		this.route1 = route1;
		this.sockinfoSrv = sockinfoSrv;
		this.param = param;
		this.lm = lm;
		this.lrc = lrc;
		this.lic = lic;
		this.legCseq = legCseq;
		this.legRoute = legRoute;
		this.legTag = legTag;
		this.legContact = legContact;
		this.legSockinfo = legSockinfo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "ruri", length = 128)
	public String getRuri() {
		return this.ruri;
	}

	public void setRuri(String ruri) {
		this.ruri = ruri;
	}

	@Column(name = "from_uri", nullable = false, length = 128)
	public String getFromUri() {
		return this.fromUri;
	}

	public void setFromUri(String fromUri) {
		this.fromUri = fromUri;
	}

	@Column(name = "to_uri", nullable = false, length = 128)
	public String getToUri() {
		return this.toUri;
	}

	public void setToUri(String toUri) {
		this.toUri = toUri;
	}

	@Column(name = "from_dname", length = 64)
	public String getFromDname() {
		return this.fromDname;
	}

	public void setFromDname(String fromDname) {
		this.fromDname = fromDname;
	}

	@Column(name = "to_dname", length = 64)
	public String getToDname() {
		return this.toDname;
	}

	public void setToDname(String toDname) {
		this.toDname = toDname;
	}

	@Column(name = "tag0", nullable = false, length = 64)
	public String getTag0() {
		return this.tag0;
	}

	public void setTag0(String tag0) {
		this.tag0 = tag0;
	}

	@Column(name = "tag1", length = 64)
	public String getTag1() {
		return this.tag1;
	}

	public void setTag1(String tag1) {
		this.tag1 = tag1;
	}

	@Column(name = "callid", nullable = false, length = 64)
	public String getCallid() {
		return this.callid;
	}

	public void setCallid(String callid) {
		this.callid = callid;
	}

	@Column(name = "cseq0", nullable = false)
	public int getCseq0() {
		return this.cseq0;
	}

	public void setCseq0(int cseq0) {
		this.cseq0 = cseq0;
	}

	@Column(name = "cseq1")
	public Integer getCseq1() {
		return this.cseq1;
	}

	public void setCseq1(Integer cseq1) {
		this.cseq1 = cseq1;
	}

	@Column(name = "contact0", nullable = false, length = 128)
	public String getContact0() {
		return this.contact0;
	}

	public void setContact0(String contact0) {
		this.contact0 = contact0;
	}

	@Column(name = "contact1", length = 128)
	public String getContact1() {
		return this.contact1;
	}

	public void setContact1(String contact1) {
		this.contact1 = contact1;
	}

	@Column(name = "route0", length = 65535)
	public String getRoute0() {
		return this.route0;
	}

	public void setRoute0(String route0) {
		this.route0 = route0;
	}

	@Column(name = "route1", length = 65535)
	public String getRoute1() {
		return this.route1;
	}

	public void setRoute1(String route1) {
		this.route1 = route1;
	}

	@Column(name = "sockinfo_srv", length = 64)
	public String getSockinfoSrv() {
		return this.sockinfoSrv;
	}

	public void setSockinfoSrv(String sockinfoSrv) {
		this.sockinfoSrv = sockinfoSrv;
	}

	@Column(name = "param", nullable = false, length = 128)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "lm", nullable = false)
	public int getLm() {
		return this.lm;
	}

	public void setLm(int lm) {
		this.lm = lm;
	}

	@Column(name = "lrc")
	public Integer getLrc() {
		return this.lrc;
	}

	public void setLrc(Integer lrc) {
		this.lrc = lrc;
	}

	@Column(name = "lic")
	public Integer getLic() {
		return this.lic;
	}

	public void setLic(Integer lic) {
		this.lic = lic;
	}

	@Column(name = "leg_cseq")
	public Integer getLegCseq() {
		return this.legCseq;
	}

	public void setLegCseq(Integer legCseq) {
		this.legCseq = legCseq;
	}

	@Column(name = "leg_route", length = 65535)
	public String getLegRoute() {
		return this.legRoute;
	}

	public void setLegRoute(String legRoute) {
		this.legRoute = legRoute;
	}

	@Column(name = "leg_tag", length = 64)
	public String getLegTag() {
		return this.legTag;
	}

	public void setLegTag(String legTag) {
		this.legTag = legTag;
	}

	@Column(name = "leg_contact", length = 128)
	public String getLegContact() {
		return this.legContact;
	}

	public void setLegContact(String legContact) {
		this.legContact = legContact;
	}

	@Column(name = "leg_sockinfo", length = 128)
	public String getLegSockinfo() {
		return this.legSockinfo;
	}

	public void setLegSockinfo(String legSockinfo) {
		this.legSockinfo = legSockinfo;
	}

}
