package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CardPropertiesId generated by hbm2java
 */
@Embeddable
public class CardPropertiesId implements java.io.Serializable {

	private long cardId;
	private String name;

	public CardPropertiesId() {
	}

	public CardPropertiesId(long cardId, String name) {
		this.cardId = cardId;
		this.name = name;
	}

	@Column(name = "Card_id", nullable = false)
	public long getCardId() {
		return this.cardId;
	}

	public void setCardId(long cardId) {
		this.cardId = cardId;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CardPropertiesId))
			return false;
		CardPropertiesId castOther = (CardPropertiesId) other;

		return (this.getCardId() == castOther.getCardId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCardId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
