package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CardProperties generated by hbm2java
 */
@Entity
@Table(name = "Card_properties", catalog = "phoenixdb")
public class CardProperties implements java.io.Serializable {

	private CardPropertiesId id;
	private Card card;
	private String value;

	public CardProperties() {
	}

	public CardProperties(CardPropertiesId id, Card card) {
		this.id = id;
		this.card = card;
	}

	public CardProperties(CardPropertiesId id, Card card, String value) {
		this.id = id;
		this.card = card;
		this.value = value;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cardId", column = @Column(name = "Card_id", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false)) })
	public CardPropertiesId getId() {
		return this.id;
	}

	public void setId(CardPropertiesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Card_id", nullable = false, insertable = false, updatable = false)
	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
