package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "Category", catalog = "phoenixdb")
public class Category implements java.io.Serializable {

	private Long id;
	private User user;
	private Category category;
	private String description;
	private String name;
	private boolean privateCategory;
	private Set categories = new HashSet(0);
	private Set cards = new HashSet(0);

	public Category() {
	}

	public Category(boolean privateCategory) {
		this.privateCategory = privateCategory;
	}

	public Category(User user, Category category, String description,
			String name, boolean privateCategory, Set categories, Set cards) {
		this.user = user;
		this.category = category;
		this.description = description;
		this.name = name;
		this.privateCategory = privateCategory;
		this.categories = categories;
		this.cards = cards;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "privateCategory", nullable = false)
	public boolean isPrivateCategory() {
		return this.privateCategory;
	}

	public void setPrivateCategory(boolean privateCategory) {
		this.privateCategory = privateCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Card_Category", catalog = "phoenixdb", joinColumns = { @JoinColumn(name = "categories_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Card_id", nullable = false, updatable = false) })
	public Set getCards() {
		return this.cards;
	}

	public void setCards(Set cards) {
		this.cards = cards;
	}

}
