package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DoNotDelete generated by hbm2java
 */
@Entity
@Table(name = "doNotDelete", catalog = "phoenixdb")
public class DoNotDelete implements java.io.Serializable {

	private int test;

	public DoNotDelete() {
	}

	public DoNotDelete(int test) {
		this.test = test;
	}

	@Id
	@Column(name = "test", nullable = false)
	public int getTest() {
		return this.test;
	}

	public void setTest(int test) {
		this.test = test;
	}

}
