package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "Image", catalog = "phoenixdb")
public class Image implements java.io.Serializable {

	private Long id;
	private Card cardByCardId;
	private Card cardByImageId;
	private Integer imageVariant;
	private String name;
	private byte[] picture;
	private String imagesKey;

	public Image() {
	}

	public Image(Card cardByCardId, Card cardByImageId, Integer imageVariant,
			String name, byte[] picture, String imagesKey) {
		this.cardByCardId = cardByCardId;
		this.cardByImageId = cardByImageId;
		this.imageVariant = imageVariant;
		this.name = name;
		this.picture = picture;
		this.imagesKey = imagesKey;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "card_id")
	public Card getCardByCardId() {
		return this.cardByCardId;
	}

	public void setCardByCardId(Card cardByCardId) {
		this.cardByCardId = cardByCardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id")
	public Card getCardByImageId() {
		return this.cardByImageId;
	}

	public void setCardByImageId(Card cardByImageId) {
		this.cardByImageId = cardByImageId;
	}

	@Column(name = "imageVariant")
	public Integer getImageVariant() {
		return this.imageVariant;
	}

	public void setImageVariant(Integer imageVariant) {
		this.imageVariant = imageVariant;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture")
	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	@Column(name = "images_KEY")
	public String getImagesKey() {
		return this.imagesKey;
	}

	public void setImagesKey(String imagesKey) {
		this.imagesKey = imagesKey;
	}

}
