package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LoadBalancer generated by hbm2java
 */
@Entity
@Table(name = "load_balancer", catalog = "phoenixdb")
public class LoadBalancer implements java.io.Serializable {

	private Integer id;
	private int groupId;
	private String dstUri;
	private String resources;
	private int probeMode;
	private String description;

	public LoadBalancer() {
	}

	public LoadBalancer(int groupId, String dstUri, String resources,
			int probeMode, String description) {
		this.groupId = groupId;
		this.dstUri = dstUri;
		this.resources = resources;
		this.probeMode = probeMode;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "group_id", nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Column(name = "dst_uri", nullable = false, length = 128)
	public String getDstUri() {
		return this.dstUri;
	}

	public void setDstUri(String dstUri) {
		this.dstUri = dstUri;
	}

	@Column(name = "resources", nullable = false)
	public String getResources() {
		return this.resources;
	}

	public void setResources(String resources) {
		this.resources = resources;
	}

	@Column(name = "probe_mode", nullable = false)
	public int getProbeMode() {
		return this.probeMode;
	}

	public void setProbeMode(int probeMode) {
		this.probeMode = probeMode;
	}

	@Column(name = "description", nullable = false, length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
