package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", catalog = "phoenixdb")
public class Location implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String contact;
	private String received;
	private String path;
	private Date expires;
	private float q;
	private String callid;
	private int cseq;
	private Date lastModified;
	private int flags;
	private int cflags;
	private String userAgent;
	private String socket;
	private Integer methods;

	public Location() {
	}

	public Location(String username, String contact, Date expires, float q,
			String callid, int cseq, Date lastModified, int flags, int cflags,
			String userAgent) {
		this.username = username;
		this.contact = contact;
		this.expires = expires;
		this.q = q;
		this.callid = callid;
		this.cseq = cseq;
		this.lastModified = lastModified;
		this.flags = flags;
		this.cflags = cflags;
		this.userAgent = userAgent;
	}

	public Location(String username, String domain, String contact,
			String received, String path, Date expires, float q, String callid,
			int cseq, Date lastModified, int flags, int cflags,
			String userAgent, String socket, Integer methods) {
		this.username = username;
		this.domain = domain;
		this.contact = contact;
		this.received = received;
		this.path = path;
		this.expires = expires;
		this.q = q;
		this.callid = callid;
		this.cseq = cseq;
		this.lastModified = lastModified;
		this.flags = flags;
		this.cflags = cflags;
		this.userAgent = userAgent;
		this.socket = socket;
		this.methods = methods;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "contact", nullable = false)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "received", length = 128)
	public String getReceived() {
		return this.received;
	}

	public void setReceived(String received) {
		this.received = received;
	}

	@Column(name = "path", length = 128)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expires", nullable = false, length = 19)
	public Date getExpires() {
		return this.expires;
	}

	public void setExpires(Date expires) {
		this.expires = expires;
	}

	@Column(name = "q", nullable = false, precision = 10)
	public float getQ() {
		return this.q;
	}

	public void setQ(float q) {
		this.q = q;
	}

	@Column(name = "callid", nullable = false)
	public String getCallid() {
		return this.callid;
	}

	public void setCallid(String callid) {
		this.callid = callid;
	}

	@Column(name = "cseq", nullable = false)
	public int getCseq() {
		return this.cseq;
	}

	public void setCseq(int cseq) {
		this.cseq = cseq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "cflags", nullable = false)
	public int getCflags() {
		return this.cflags;
	}

	public void setCflags(int cflags) {
		this.cflags = cflags;
	}

	@Column(name = "user_agent", nullable = false)
	public String getUserAgent() {
		return this.userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Column(name = "socket", length = 64)
	public String getSocket() {
		return this.socket;
	}

	public void setSocket(String socket) {
		this.socket = socket;
	}

	@Column(name = "methods")
	public Integer getMethods() {
		return this.methods;
	}

	public void setMethods(Integer methods) {
		this.methods = methods;
	}

}
