package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SpeedDial generated by hbm2java
 */
@Entity
@Table(name = "speed_dial", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"username", "domain", "sd_domain", "sd_username" }))
public class SpeedDial implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String sdUsername;
	private String sdDomain;
	private String newUri;
	private String fname;
	private String lname;
	private String description;

	public SpeedDial() {
	}

	public SpeedDial(String username, String domain, String sdUsername,
			String sdDomain, String newUri, String fname, String lname,
			String description) {
		this.username = username;
		this.domain = domain;
		this.sdUsername = sdUsername;
		this.sdDomain = sdDomain;
		this.newUri = newUri;
		this.fname = fname;
		this.lname = lname;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "sd_username", nullable = false, length = 64)
	public String getSdUsername() {
		return this.sdUsername;
	}

	public void setSdUsername(String sdUsername) {
		this.sdUsername = sdUsername;
	}

	@Column(name = "sd_domain", nullable = false, length = 64)
	public String getSdDomain() {
		return this.sdDomain;
	}

	public void setSdDomain(String sdDomain) {
		this.sdDomain = sdDomain;
	}

	@Column(name = "new_uri", nullable = false, length = 128)
	public String getNewUri() {
		return this.newUri;
	}

	public void setNewUri(String newUri) {
		this.newUri = newUri;
	}

	@Column(name = "fname", nullable = false, length = 64)
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "lname", nullable = false, length = 64)
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "description", nullable = false, length = 64)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
