package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "User", catalog = "phoenixdb")
public class User implements java.io.Serializable {

	private Long userId;
	private String authority;
	private String email;
	private String firstName;
	private Date lastAccess;
	private String lastIp;
	private String login;
	private String password;
	private Date registrationDate;
	private int role;
	private String surName;
	private Set userCards = new HashSet(0);
	private Set cards = new HashSet(0);
	private Set categories = new HashSet(0);

	public User() {
	}

	public User(int role) {
		this.role = role;
	}

	public User(String authority, String email, String firstName,
			Date lastAccess, String lastIp, String login, String password,
			Date registrationDate, int role, String surName, Set userCards,
			Set cards, Set categories) {
		this.authority = authority;
		this.email = email;
		this.firstName = firstName;
		this.lastAccess = lastAccess;
		this.lastIp = lastIp;
		this.login = login;
		this.password = password;
		this.registrationDate = registrationDate;
		this.role = role;
		this.surName = surName;
		this.userCards = userCards;
		this.cards = cards;
		this.categories = categories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_id", unique = true, nullable = false)
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "authority")
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstName")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastAccess", length = 19)
	public Date getLastAccess() {
		return this.lastAccess;
	}

	public void setLastAccess(Date lastAccess) {
		this.lastAccess = lastAccess;
	}

	@Column(name = "lastIP")
	public String getLastIp() {
		return this.lastIp;
	}

	public void setLastIp(String lastIp) {
		this.lastIp = lastIp;
	}

	@Column(name = "login")
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registrationDate", length = 19)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "role", nullable = false)
	public int getRole() {
		return this.role;
	}

	public void setRole(int role) {
		this.role = role;
	}

	@Column(name = "surName")
	public String getSurName() {
		return this.surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getUserCards() {
		return this.userCards;
	}

	public void setUserCards(Set userCards) {
		this.userCards = userCards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getCards() {
		return this.cards;
	}

	public void setCards(Set cards) {
		this.cards = cards;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

}
