package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserCardId generated by hbm2java
 */
@Embeddable
public class UserCardId implements java.io.Serializable {

	private long userUserId;
	private long cardsId;

	public UserCardId() {
	}

	public UserCardId(long userUserId, long cardsId) {
		this.userUserId = userUserId;
		this.cardsId = cardsId;
	}

	@Column(name = "User_user_id", nullable = false)
	public long getUserUserId() {
		return this.userUserId;
	}

	public void setUserUserId(long userUserId) {
		this.userUserId = userUserId;
	}

	@Column(name = "cards_id", unique = true, nullable = false)
	public long getCardsId() {
		return this.cardsId;
	}

	public void setCardsId(long cardsId) {
		this.cardsId = cardsId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserCardId))
			return false;
		UserCardId castOther = (UserCardId) other;

		return (this.getUserUserId() == castOther.getUserUserId())
				&& (this.getCardsId() == castOther.getCardsId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserUserId();
		result = 37 * result + (int) this.getCardsId();
		return result;
	}

}
