package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserCard generated by hbm2java
 */
@Entity
@Table(name = "User_Card", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = "cards_id"))
public class UserCard implements java.io.Serializable {

	private UserCardId id;
	private Card card;
	private User user;

	public UserCard() {
	}

	public UserCard(UserCardId id, Card card, User user) {
		this.id = id;
		this.card = card;
		this.user = user;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userUserId", column = @Column(name = "User_user_id", nullable = false)),
			@AttributeOverride(name = "cardsId", column = @Column(name = "cards_id", unique = true, nullable = false)) })
	public UserCardId getId() {
		return this.id;
	}

	public void setId(UserCardId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cards_id", unique = true, nullable = false, insertable = false, updatable = false)
	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "User_user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
