package com.phoenix.db;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Whitelist generated by hbm2java
 */
@Entity
@Table(name = "whitelist", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"src", "src_type", "dst", "dst_type" }))
public class Whitelist implements java.io.Serializable {

	private Long id;
	private int src;
	private String srcType;
	private int dst;
	private String dstType;
	private String action;

	public Whitelist() {
	}

	public Whitelist(int src, String srcType, int dst, String dstType,
			String action) {
		this.src = src;
		this.srcType = srcType;
		this.dst = dst;
		this.dstType = dstType;
		this.action = action;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "src", nullable = false)
	public int getSrc() {
		return this.src;
	}

	public void setSrc(int src) {
		this.src = src;
	}

	@Column(name = "src_type", nullable = false, length = 6)
	public String getSrcType() {
		return this.srcType;
	}

	public void setSrcType(String srcType) {
		this.srcType = srcType;
	}

	@Column(name = "dst", nullable = false)
	public int getDst() {
		return this.dst;
	}

	public void setDst(int dst) {
		this.dst = dst;
	}

	@Column(name = "dst_type", nullable = false, length = 6)
	public String getDstType() {
		return this.dstType;
	}

	public void setDstType(String dstType) {
		this.dstType = dstType;
	}

	@Column(name = "action", nullable = false, length = 6)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
