SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE Card_Category;
TRUNCATE TABLE Card_properties;
TRUNCATE TABLE User_Card;

TRUNCATE TABLE Card;
TRUNCATE TABLE Category;
TRUNCATE TABLE User;
SET FOREIGN_KEY_CHECKS=1;
