package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acc generated by hbm2java
 */
@Entity
@Table(name = "acc", catalog = "phoenixdb")
public class Acc implements java.io.Serializable {

	private Integer id;
	private String method;
	private String fromTag;
	private String toTag;
	private String callid;
	private String sipCode;
	private String sipReason;
	private Date time;
	private int duration;
	private int setuptime;
	private Date created;

	public Acc() {
	}

	public Acc(String method, String fromTag, String toTag, String callid,
			String sipCode, String sipReason, Date time, int duration,
			int setuptime, Date created) {
		this.method = method;
		this.fromTag = fromTag;
		this.toTag = toTag;
		this.callid = callid;
		this.sipCode = sipCode;
		this.sipReason = sipReason;
		this.time = time;
		this.duration = duration;
		this.setuptime = setuptime;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "method", nullable = false, length = 16)
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "from_tag", nullable = false, length = 64)
	public String getFromTag() {
		return this.fromTag;
	}

	public void setFromTag(String fromTag) {
		this.fromTag = fromTag;
	}

	@Column(name = "to_tag", nullable = false, length = 64)
	public String getToTag() {
		return this.toTag;
	}

	public void setToTag(String toTag) {
		this.toTag = toTag;
	}

	@Column(name = "callid", nullable = false, length = 64)
	public String getCallid() {
		return this.callid;
	}

	public void setCallid(String callid) {
		this.callid = callid;
	}

	@Column(name = "sip_code", nullable = false, length = 3)
	public String getSipCode() {
		return this.sipCode;
	}

	public void setSipCode(String sipCode) {
		this.sipCode = sipCode;
	}

	@Column(name = "sip_reason", nullable = false, length = 32)
	public String getSipReason() {
		return this.sipReason;
	}

	public void setSipReason(String sipReason) {
		this.sipReason = sipReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", nullable = false, length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@Column(name = "duration", nullable = false)
	public int getDuration() {
		return this.duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	@Column(name = "setuptime", nullable = false)
	public int getSetuptime() {
		return this.setuptime;
	}

	public void setSetuptime(int setuptime) {
		this.setuptime = setuptime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
