package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "phoenixdb")
public class Address implements java.io.Serializable {

	private Integer id;
	private short grp;
	private String ip;
	private byte mask;
	private short port;
	private String proto;
	private String pattern;
	private String contextInfo;

	public Address() {
	}

	public Address(short grp, String ip, byte mask, short port, String proto) {
		this.grp = grp;
		this.ip = ip;
		this.mask = mask;
		this.port = port;
		this.proto = proto;
	}

	public Address(short grp, String ip, byte mask, short port, String proto,
			String pattern, String contextInfo) {
		this.grp = grp;
		this.ip = ip;
		this.mask = mask;
		this.port = port;
		this.proto = proto;
		this.pattern = pattern;
		this.contextInfo = contextInfo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "grp", nullable = false)
	public short getGrp() {
		return this.grp;
	}

	public void setGrp(short grp) {
		this.grp = grp;
	}

	@Column(name = "ip", nullable = false, length = 50)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "mask", nullable = false)
	public byte getMask() {
		return this.mask;
	}

	public void setMask(byte mask) {
		this.mask = mask;
	}

	@Column(name = "port", nullable = false)
	public short getPort() {
		return this.port;
	}

	public void setPort(short port) {
		this.port = port;
	}

	@Column(name = "proto", nullable = false, length = 4)
	public String getProto() {
		return this.proto;
	}

	public void setProto(String proto) {
		this.proto = proto;
	}

	@Column(name = "pattern", length = 64)
	public String getPattern() {
		return this.pattern;
	}

	public void setPattern(String pattern) {
		this.pattern = pattern;
	}

	@Column(name = "context_info", length = 32)
	public String getContextInfo() {
		return this.contextInfo;
	}

	public void setContextInfo(String contextInfo) {
		this.contextInfo = contextInfo;
	}

}
