package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * B2bLogic generated by hbm2java
 */
@Entity
@Table(name = "b2b_logic", uniqueConstraints = @UniqueConstraint(columnNames = "si_key"))
public class B2bLogic implements java.io.Serializable {

	private Integer id;
	private String siKey;
	private String scenario;
	private Integer sstate;
	private Integer nextSstate;
	private String sparam0;
	private String sparam1;
	private String sparam2;
	private String sparam3;
	private String sparam4;
	private String sdp;
	private Integer e1Type;
	private String e1Sid;
	private String e1From;
	private String e1To;
	private String e1Key;
	private Integer e2Type;
	private String e2Sid;
	private String e2From;
	private String e2To;
	private String e2Key;
	private Integer e3Type;
	private String e3Sid;
	private String e3From;
	private String e3To;
	private String e3Key;

	public B2bLogic() {
	}

	public B2bLogic(String siKey, String scenario, String sparam0,
			String sparam1, String sparam2, String sparam3, String sparam4,
			String sdp, String e1Sid, String e1From, String e1To, String e1Key,
			String e2Sid, String e2From, String e2To, String e2Key,
			String e3Sid, String e3From, String e3To, String e3Key) {
		this.siKey = siKey;
		this.scenario = scenario;
		this.sparam0 = sparam0;
		this.sparam1 = sparam1;
		this.sparam2 = sparam2;
		this.sparam3 = sparam3;
		this.sparam4 = sparam4;
		this.sdp = sdp;
		this.e1Sid = e1Sid;
		this.e1From = e1From;
		this.e1To = e1To;
		this.e1Key = e1Key;
		this.e2Sid = e2Sid;
		this.e2From = e2From;
		this.e2To = e2To;
		this.e2Key = e2Key;
		this.e3Sid = e3Sid;
		this.e3From = e3From;
		this.e3To = e3To;
		this.e3Key = e3Key;
	}

	public B2bLogic(String siKey, String scenario, Integer sstate,
			Integer nextSstate, String sparam0, String sparam1, String sparam2,
			String sparam3, String sparam4, String sdp, Integer e1Type,
			String e1Sid, String e1From, String e1To, String e1Key,
			Integer e2Type, String e2Sid, String e2From, String e2To,
			String e2Key, Integer e3Type, String e3Sid, String e3From,
			String e3To, String e3Key) {
		this.siKey = siKey;
		this.scenario = scenario;
		this.sstate = sstate;
		this.nextSstate = nextSstate;
		this.sparam0 = sparam0;
		this.sparam1 = sparam1;
		this.sparam2 = sparam2;
		this.sparam3 = sparam3;
		this.sparam4 = sparam4;
		this.sdp = sdp;
		this.e1Type = e1Type;
		this.e1Sid = e1Sid;
		this.e1From = e1From;
		this.e1To = e1To;
		this.e1Key = e1Key;
		this.e2Type = e2Type;
		this.e2Sid = e2Sid;
		this.e2From = e2From;
		this.e2To = e2To;
		this.e2Key = e2Key;
		this.e3Type = e3Type;
		this.e3Sid = e3Sid;
		this.e3From = e3From;
		this.e3To = e3To;
		this.e3Key = e3Key;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "si_key", unique = true, nullable = false, length = 64)
	public String getSiKey() {
		return this.siKey;
	}

	public void setSiKey(String siKey) {
		this.siKey = siKey;
	}

	@Column(name = "scenario", nullable = false, length = 64)
	public String getScenario() {
		return this.scenario;
	}

	public void setScenario(String scenario) {
		this.scenario = scenario;
	}

	@Column(name = "sstate")
	public Integer getSstate() {
		return this.sstate;
	}

	public void setSstate(Integer sstate) {
		this.sstate = sstate;
	}

	@Column(name = "next_sstate")
	public Integer getNextSstate() {
		return this.nextSstate;
	}

	public void setNextSstate(Integer nextSstate) {
		this.nextSstate = nextSstate;
	}

	@Column(name = "sparam0", nullable = false, length = 64)
	public String getSparam0() {
		return this.sparam0;
	}

	public void setSparam0(String sparam0) {
		this.sparam0 = sparam0;
	}

	@Column(name = "sparam1", nullable = false, length = 64)
	public String getSparam1() {
		return this.sparam1;
	}

	public void setSparam1(String sparam1) {
		this.sparam1 = sparam1;
	}

	@Column(name = "sparam2", nullable = false, length = 64)
	public String getSparam2() {
		return this.sparam2;
	}

	public void setSparam2(String sparam2) {
		this.sparam2 = sparam2;
	}

	@Column(name = "sparam3", nullable = false, length = 64)
	public String getSparam3() {
		return this.sparam3;
	}

	public void setSparam3(String sparam3) {
		this.sparam3 = sparam3;
	}

	@Column(name = "sparam4", nullable = false, length = 64)
	public String getSparam4() {
		return this.sparam4;
	}

	public void setSparam4(String sparam4) {
		this.sparam4 = sparam4;
	}

	@Column(name = "sdp", nullable = false)
	public String getSdp() {
		return this.sdp;
	}

	public void setSdp(String sdp) {
		this.sdp = sdp;
	}

	@Column(name = "e1_type")
	public Integer getE1Type() {
		return this.e1Type;
	}

	public void setE1Type(Integer e1Type) {
		this.e1Type = e1Type;
	}

	@Column(name = "e1_sid", nullable = false, length = 64)
	public String getE1Sid() {
		return this.e1Sid;
	}

	public void setE1Sid(String e1Sid) {
		this.e1Sid = e1Sid;
	}

	@Column(name = "e1_from", nullable = false, length = 128)
	public String getE1From() {
		return this.e1From;
	}

	public void setE1From(String e1From) {
		this.e1From = e1From;
	}

	@Column(name = "e1_to", nullable = false, length = 128)
	public String getE1To() {
		return this.e1To;
	}

	public void setE1To(String e1To) {
		this.e1To = e1To;
	}

	@Column(name = "e1_key", nullable = false, length = 64)
	public String getE1Key() {
		return this.e1Key;
	}

	public void setE1Key(String e1Key) {
		this.e1Key = e1Key;
	}

	@Column(name = "e2_type")
	public Integer getE2Type() {
		return this.e2Type;
	}

	public void setE2Type(Integer e2Type) {
		this.e2Type = e2Type;
	}

	@Column(name = "e2_sid", nullable = false, length = 64)
	public String getE2Sid() {
		return this.e2Sid;
	}

	public void setE2Sid(String e2Sid) {
		this.e2Sid = e2Sid;
	}

	@Column(name = "e2_from", nullable = false, length = 128)
	public String getE2From() {
		return this.e2From;
	}

	public void setE2From(String e2From) {
		this.e2From = e2From;
	}

	@Column(name = "e2_to", nullable = false, length = 128)
	public String getE2To() {
		return this.e2To;
	}

	public void setE2To(String e2To) {
		this.e2To = e2To;
	}

	@Column(name = "e2_key", nullable = false, length = 64)
	public String getE2Key() {
		return this.e2Key;
	}

	public void setE2Key(String e2Key) {
		this.e2Key = e2Key;
	}

	@Column(name = "e3_type")
	public Integer getE3Type() {
		return this.e3Type;
	}

	public void setE3Type(Integer e3Type) {
		this.e3Type = e3Type;
	}

	@Column(name = "e3_sid", nullable = false, length = 64)
	public String getE3Sid() {
		return this.e3Sid;
	}

	public void setE3Sid(String e3Sid) {
		this.e3Sid = e3Sid;
	}

	@Column(name = "e3_from", nullable = false, length = 128)
	public String getE3From() {
		return this.e3From;
	}

	public void setE3From(String e3From) {
		this.e3From = e3From;
	}

	@Column(name = "e3_to", nullable = false, length = 128)
	public String getE3To() {
		return this.e3To;
	}

	public void setE3To(String e3To) {
		this.e3To = e3To;
	}

	@Column(name = "e3_key", nullable = false, length = 64)
	public String getE3Key() {
		return this.e3Key;
	}

	public void setE3Key(String e3Key) {
		this.e3Key = e3Key;
	}

}
