package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Carrierroute generated by hbm2java
 */
@Entity
@Table(name = "carrierroute")
public class Carrierroute implements java.io.Serializable {

	private Integer id;
	private int carrier;
	private String domain;
	private String scanPrefix;
	private int flags;
	private int mask;
	private float prob;
	private int strip;
	private String rewriteHost;
	private String rewritePrefix;
	private String rewriteSuffix;
	private String description;

	public Carrierroute() {
	}

	public Carrierroute(int carrier, String domain, String scanPrefix,
			int flags, int mask, float prob, int strip, String rewriteHost,
			String rewritePrefix, String rewriteSuffix) {
		this.carrier = carrier;
		this.domain = domain;
		this.scanPrefix = scanPrefix;
		this.flags = flags;
		this.mask = mask;
		this.prob = prob;
		this.strip = strip;
		this.rewriteHost = rewriteHost;
		this.rewritePrefix = rewritePrefix;
		this.rewriteSuffix = rewriteSuffix;
	}

	public Carrierroute(int carrier, String domain, String scanPrefix,
			int flags, int mask, float prob, int strip, String rewriteHost,
			String rewritePrefix, String rewriteSuffix, String description) {
		this.carrier = carrier;
		this.domain = domain;
		this.scanPrefix = scanPrefix;
		this.flags = flags;
		this.mask = mask;
		this.prob = prob;
		this.strip = strip;
		this.rewriteHost = rewriteHost;
		this.rewritePrefix = rewritePrefix;
		this.rewriteSuffix = rewriteSuffix;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "carrier", nullable = false)
	public int getCarrier() {
		return this.carrier;
	}

	public void setCarrier(int carrier) {
		this.carrier = carrier;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "scan_prefix", nullable = false, length = 64)
	public String getScanPrefix() {
		return this.scanPrefix;
	}

	public void setScanPrefix(String scanPrefix) {
		this.scanPrefix = scanPrefix;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "mask", nullable = false)
	public int getMask() {
		return this.mask;
	}

	public void setMask(int mask) {
		this.mask = mask;
	}

	@Column(name = "prob", nullable = false, precision = 12, scale = 0)
	public float getProb() {
		return this.prob;
	}

	public void setProb(float prob) {
		this.prob = prob;
	}

	@Column(name = "strip", nullable = false)
	public int getStrip() {
		return this.strip;
	}

	public void setStrip(int strip) {
		this.strip = strip;
	}

	@Column(name = "rewrite_host", nullable = false, length = 128)
	public String getRewriteHost() {
		return this.rewriteHost;
	}

	public void setRewriteHost(String rewriteHost) {
		this.rewriteHost = rewriteHost;
	}

	@Column(name = "rewrite_prefix", nullable = false, length = 64)
	public String getRewritePrefix() {
		return this.rewritePrefix;
	}

	public void setRewritePrefix(String rewritePrefix) {
		this.rewritePrefix = rewritePrefix;
	}

	@Column(name = "rewrite_suffix", nullable = false, length = 64)
	public String getRewriteSuffix() {
		return this.rewriteSuffix;
	}

	public void setRewriteSuffix(String rewriteSuffix) {
		this.rewriteSuffix = rewriteSuffix;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
