package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Carrierfailureroute generated by hbm2java
 */
@Entity
@Table(name = "carrierfailureroute")
public class Carrierfailureroute implements java.io.Serializable {

	private Integer id;
	private int carrier;
	private String domain;
	private String scanPrefix;
	private String hostName;
	private String replyCode;
	private int flags;
	private int mask;
	private String nextDomain;
	private String description;

	public Carrierfailureroute() {
	}

	public Carrierfailureroute(int carrier, String domain, String scanPrefix,
			String hostName, String replyCode, int flags, int mask,
			String nextDomain) {
		this.carrier = carrier;
		this.domain = domain;
		this.scanPrefix = scanPrefix;
		this.hostName = hostName;
		this.replyCode = replyCode;
		this.flags = flags;
		this.mask = mask;
		this.nextDomain = nextDomain;
	}

	public Carrierfailureroute(int carrier, String domain, String scanPrefix,
			String hostName, String replyCode, int flags, int mask,
			String nextDomain, String description) {
		this.carrier = carrier;
		this.domain = domain;
		this.scanPrefix = scanPrefix;
		this.hostName = hostName;
		this.replyCode = replyCode;
		this.flags = flags;
		this.mask = mask;
		this.nextDomain = nextDomain;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "carrier", nullable = false)
	public int getCarrier() {
		return this.carrier;
	}

	public void setCarrier(int carrier) {
		this.carrier = carrier;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "scan_prefix", nullable = false, length = 64)
	public String getScanPrefix() {
		return this.scanPrefix;
	}

	public void setScanPrefix(String scanPrefix) {
		this.scanPrefix = scanPrefix;
	}

	@Column(name = "host_name", nullable = false, length = 128)
	public String getHostName() {
		return this.hostName;
	}

	public void setHostName(String hostName) {
		this.hostName = hostName;
	}

	@Column(name = "reply_code", nullable = false, length = 3)
	public String getReplyCode() {
		return this.replyCode;
	}

	public void setReplyCode(String replyCode) {
		this.replyCode = replyCode;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "mask", nullable = false)
	public int getMask() {
		return this.mask;
	}

	public void setMask(int mask) {
		this.mask = mask;
	}

	@Column(name = "next_domain", nullable = false, length = 64)
	public String getNextDomain() {
		return this.nextDomain;
	}

	public void setNextDomain(String nextDomain) {
		this.nextDomain = nextDomain;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
