package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cpl generated by hbm2java
 */
@Entity
@Table(name = "cpl", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"username", "domain" }))
public class Cpl implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String cplXml;
	private String cplBin;

	public Cpl() {
	}

	public Cpl(String username, String domain) {
		this.username = username;
		this.domain = domain;
	}

	public Cpl(String username, String domain, String cplXml, String cplBin) {
		this.username = username;
		this.domain = domain;
		this.cplXml = cplXml;
		this.cplBin = cplBin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "cpl_xml", length = 65535)
	public String getCplXml() {
		return this.cplXml;
	}

	public void setCplXml(String cplXml) {
		this.cplXml = cplXml;
	}

	@Column(name = "cpl_bin", length = 65535)
	public String getCplBin() {
		return this.cplBin;
	}

	public void setCplBin(String cplBin) {
		this.cplBin = cplBin;
	}

}
