package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Dbaliases generated by hbm2java
 */
@Entity
@Table(name = "dbaliases", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"alias_username", "alias_domain" }))
public class Dbaliases implements java.io.Serializable {

	private Integer id;
	private String aliasUsername;
	private String aliasDomain;
	private String username;
	private String domain;

	public Dbaliases() {
	}

	public Dbaliases(String aliasUsername, String aliasDomain, String username,
			String domain) {
		this.aliasUsername = aliasUsername;
		this.aliasDomain = aliasDomain;
		this.username = username;
		this.domain = domain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "alias_username", nullable = false, length = 64)
	public String getAliasUsername() {
		return this.aliasUsername;
	}

	public void setAliasUsername(String aliasUsername) {
		this.aliasUsername = aliasUsername;
	}

	@Column(name = "alias_domain", nullable = false, length = 64)
	public String getAliasDomain() {
		return this.aliasDomain;
	}

	public void setAliasDomain(String aliasDomain) {
		this.aliasDomain = aliasDomain;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

}
