package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dialog generated by hbm2java
 */
@Entity
@Table(name = "dialog")
public class Dialog implements java.io.Serializable {

	private Integer id;
	private int hashEntry;
	private int hashId;
	private String callid;
	private String fromUri;
	private String fromTag;
	private String toUri;
	private String toTag;
	private String callerCseq;
	private String calleeCseq;
	private String callerRouteSet;
	private String calleeRouteSet;
	private String callerContact;
	private String calleeContact;
	private String callerSock;
	private String calleeSock;
	private int state;
	private int startTime;
	private int timeout;
	private String vars;
	private String profiles;
	private int scriptFlags;

	public Dialog() {
	}

	public Dialog(int hashEntry, int hashId, String callid, String fromUri,
			String fromTag, String toUri, String toTag, String callerCseq,
			String calleeCseq, String callerContact, String calleeContact,
			String callerSock, String calleeSock, int state, int startTime,
			int timeout, int scriptFlags) {
		this.hashEntry = hashEntry;
		this.hashId = hashId;
		this.callid = callid;
		this.fromUri = fromUri;
		this.fromTag = fromTag;
		this.toUri = toUri;
		this.toTag = toTag;
		this.callerCseq = callerCseq;
		this.calleeCseq = calleeCseq;
		this.callerContact = callerContact;
		this.calleeContact = calleeContact;
		this.callerSock = callerSock;
		this.calleeSock = calleeSock;
		this.state = state;
		this.startTime = startTime;
		this.timeout = timeout;
		this.scriptFlags = scriptFlags;
	}

	public Dialog(int hashEntry, int hashId, String callid, String fromUri,
			String fromTag, String toUri, String toTag, String callerCseq,
			String calleeCseq, String callerRouteSet, String calleeRouteSet,
			String callerContact, String calleeContact, String callerSock,
			String calleeSock, int state, int startTime, int timeout,
			String vars, String profiles, int scriptFlags) {
		this.hashEntry = hashEntry;
		this.hashId = hashId;
		this.callid = callid;
		this.fromUri = fromUri;
		this.fromTag = fromTag;
		this.toUri = toUri;
		this.toTag = toTag;
		this.callerCseq = callerCseq;
		this.calleeCseq = calleeCseq;
		this.callerRouteSet = callerRouteSet;
		this.calleeRouteSet = calleeRouteSet;
		this.callerContact = callerContact;
		this.calleeContact = calleeContact;
		this.callerSock = callerSock;
		this.calleeSock = calleeSock;
		this.state = state;
		this.startTime = startTime;
		this.timeout = timeout;
		this.vars = vars;
		this.profiles = profiles;
		this.scriptFlags = scriptFlags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "hash_entry", nullable = false)
	public int getHashEntry() {
		return this.hashEntry;
	}

	public void setHashEntry(int hashEntry) {
		this.hashEntry = hashEntry;
	}

	@Column(name = "hash_id", nullable = false)
	public int getHashId() {
		return this.hashId;
	}

	public void setHashId(int hashId) {
		this.hashId = hashId;
	}

	@Column(name = "callid", nullable = false)
	public String getCallid() {
		return this.callid;
	}

	public void setCallid(String callid) {
		this.callid = callid;
	}

	@Column(name = "from_uri", nullable = false, length = 128)
	public String getFromUri() {
		return this.fromUri;
	}

	public void setFromUri(String fromUri) {
		this.fromUri = fromUri;
	}

	@Column(name = "from_tag", nullable = false, length = 64)
	public String getFromTag() {
		return this.fromTag;
	}

	public void setFromTag(String fromTag) {
		this.fromTag = fromTag;
	}

	@Column(name = "to_uri", nullable = false, length = 128)
	public String getToUri() {
		return this.toUri;
	}

	public void setToUri(String toUri) {
		this.toUri = toUri;
	}

	@Column(name = "to_tag", nullable = false, length = 64)
	public String getToTag() {
		return this.toTag;
	}

	public void setToTag(String toTag) {
		this.toTag = toTag;
	}

	@Column(name = "caller_cseq", nullable = false, length = 11)
	public String getCallerCseq() {
		return this.callerCseq;
	}

	public void setCallerCseq(String callerCseq) {
		this.callerCseq = callerCseq;
	}

	@Column(name = "callee_cseq", nullable = false, length = 11)
	public String getCalleeCseq() {
		return this.calleeCseq;
	}

	public void setCalleeCseq(String calleeCseq) {
		this.calleeCseq = calleeCseq;
	}

	@Column(name = "caller_route_set", length = 65535)
	public String getCallerRouteSet() {
		return this.callerRouteSet;
	}

	public void setCallerRouteSet(String callerRouteSet) {
		this.callerRouteSet = callerRouteSet;
	}

	@Column(name = "callee_route_set", length = 65535)
	public String getCalleeRouteSet() {
		return this.calleeRouteSet;
	}

	public void setCalleeRouteSet(String calleeRouteSet) {
		this.calleeRouteSet = calleeRouteSet;
	}

	@Column(name = "caller_contact", nullable = false, length = 128)
	public String getCallerContact() {
		return this.callerContact;
	}

	public void setCallerContact(String callerContact) {
		this.callerContact = callerContact;
	}

	@Column(name = "callee_contact", nullable = false, length = 128)
	public String getCalleeContact() {
		return this.calleeContact;
	}

	public void setCalleeContact(String calleeContact) {
		this.calleeContact = calleeContact;
	}

	@Column(name = "caller_sock", nullable = false, length = 64)
	public String getCallerSock() {
		return this.callerSock;
	}

	public void setCallerSock(String callerSock) {
		this.callerSock = callerSock;
	}

	@Column(name = "callee_sock", nullable = false, length = 64)
	public String getCalleeSock() {
		return this.calleeSock;
	}

	public void setCalleeSock(String calleeSock) {
		this.calleeSock = calleeSock;
	}

	@Column(name = "state", nullable = false)
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

	@Column(name = "start_time", nullable = false)
	public int getStartTime() {
		return this.startTime;
	}

	public void setStartTime(int startTime) {
		this.startTime = startTime;
	}

	@Column(name = "timeout", nullable = false)
	public int getTimeout() {
		return this.timeout;
	}

	public void setTimeout(int timeout) {
		this.timeout = timeout;
	}

	@Column(name = "vars", length = 65535)
	public String getVars() {
		return this.vars;
	}

	public void setVars(String vars) {
		this.vars = vars;
	}

	@Column(name = "profiles", length = 65535)
	public String getProfiles() {
		return this.profiles;
	}

	public void setProfiles(String profiles) {
		this.profiles = profiles;
	}

	@Column(name = "script_flags", nullable = false)
	public int getScriptFlags() {
		return this.scriptFlags;
	}

	public void setScriptFlags(int scriptFlags) {
		this.scriptFlags = scriptFlags;
	}

}
