package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dialplan generated by hbm2java
 */
@Entity
@Table(name = "dialplan")
public class Dialplan implements java.io.Serializable {

	private Integer id;
	private int dpid;
	private int pr;
	private int matchOp;
	private String matchExp;
	private int matchLen;
	private String substExp;
	private String replExp;
	private String attrs;

	public Dialplan() {
	}

	public Dialplan(int dpid, int pr, int matchOp, String matchExp,
			int matchLen, String substExp, String replExp, String attrs) {
		this.dpid = dpid;
		this.pr = pr;
		this.matchOp = matchOp;
		this.matchExp = matchExp;
		this.matchLen = matchLen;
		this.substExp = substExp;
		this.replExp = replExp;
		this.attrs = attrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "dpid", nullable = false)
	public int getDpid() {
		return this.dpid;
	}

	public void setDpid(int dpid) {
		this.dpid = dpid;
	}

	@Column(name = "pr", nullable = false)
	public int getPr() {
		return this.pr;
	}

	public void setPr(int pr) {
		this.pr = pr;
	}

	@Column(name = "match_op", nullable = false)
	public int getMatchOp() {
		return this.matchOp;
	}

	public void setMatchOp(int matchOp) {
		this.matchOp = matchOp;
	}

	@Column(name = "match_exp", nullable = false, length = 64)
	public String getMatchExp() {
		return this.matchExp;
	}

	public void setMatchExp(String matchExp) {
		this.matchExp = matchExp;
	}

	@Column(name = "match_len", nullable = false)
	public int getMatchLen() {
		return this.matchLen;
	}

	public void setMatchLen(int matchLen) {
		this.matchLen = matchLen;
	}

	@Column(name = "subst_exp", nullable = false, length = 64)
	public String getSubstExp() {
		return this.substExp;
	}

	public void setSubstExp(String substExp) {
		this.substExp = substExp;
	}

	@Column(name = "repl_exp", nullable = false, length = 32)
	public String getReplExp() {
		return this.replExp;
	}

	public void setReplExp(String replExp) {
		this.replExp = replExp;
	}

	@Column(name = "attrs", nullable = false, length = 32)
	public String getAttrs() {
		return this.attrs;
	}

	public void setAttrs(String attrs) {
		this.attrs = attrs;
	}

}
