package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dispatcher generated by hbm2java
 */
@Entity
@Table(name = "dispatcher", catalog = "phoenixdb")
public class Dispatcher implements java.io.Serializable {

	private Integer id;
	private int setid;
	private String destination;
	private int flags;
	private int weight;
	private String attrs;
	private String description;

	public Dispatcher() {
	}

	public Dispatcher(int setid, String destination, int flags, int weight,
			String attrs, String description) {
		this.setid = setid;
		this.destination = destination;
		this.flags = flags;
		this.weight = weight;
		this.attrs = attrs;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "setid", nullable = false)
	public int getSetid() {
		return this.setid;
	}

	public void setSetid(int setid) {
		this.setid = setid;
	}

	@Column(name = "destination", nullable = false, length = 192)
	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "weight", nullable = false)
	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	@Column(name = "attrs", nullable = false, length = 128)
	public String getAttrs() {
		return this.attrs;
	}

	public void setAttrs(String attrs) {
		this.attrs = attrs;
	}

	@Column(name = "description", nullable = false, length = 64)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
