package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Domainpolicy generated by hbm2java
 */
@Entity
@Table(name = "domainpolicy", uniqueConstraints = @UniqueConstraint(columnNames = {
		"rule", "att", "val" }))
public class Domainpolicy implements java.io.Serializable {

	private Integer id;
	private String rule;
	private String type;
	private String att;
	private String val;
	private String description;

	public Domainpolicy() {
	}

	public Domainpolicy(String rule, String type, String description) {
		this.rule = rule;
		this.type = type;
		this.description = description;
	}

	public Domainpolicy(String rule, String type, String att, String val,
			String description) {
		this.rule = rule;
		this.type = type;
		this.att = att;
		this.val = val;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rule", nullable = false)
	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "att")
	public String getAtt() {
		return this.att;
	}

	public void setAtt(String att) {
		this.att = att;
	}

	@Column(name = "val", length = 128)
	public String getVal() {
		return this.val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
