package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DrGwLists generated by hbm2java
 */
@Entity
@Table(name = "dr_gw_lists")
public class DrGwLists implements java.io.Serializable {

	private Integer id;
	private String gwlist;
	private String description;

	public DrGwLists() {
	}

	public DrGwLists(String gwlist, String description) {
		this.gwlist = gwlist;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "gwlist", nullable = false)
	public String getGwlist() {
		return this.gwlist;
	}

	public void setGwlist(String gwlist) {
		this.gwlist = gwlist;
	}

	@Column(name = "description", nullable = false, length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
