package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DrRules generated by hbm2java
 */
@Entity
@Table(name = "dr_rules")
public class DrRules implements java.io.Serializable {

	private Integer ruleid;
	private String groupid;
	private String prefix;
	private String timerec;
	private int priority;
	private String routeid;
	private String gwlist;
	private String attrs;
	private String description;

	public DrRules() {
	}

	public DrRules(String groupid, String prefix, String timerec, int priority,
			String routeid, String gwlist, String description) {
		this.groupid = groupid;
		this.prefix = prefix;
		this.timerec = timerec;
		this.priority = priority;
		this.routeid = routeid;
		this.gwlist = gwlist;
		this.description = description;
	}

	public DrRules(String groupid, String prefix, String timerec, int priority,
			String routeid, String gwlist, String attrs, String description) {
		this.groupid = groupid;
		this.prefix = prefix;
		this.timerec = timerec;
		this.priority = priority;
		this.routeid = routeid;
		this.gwlist = gwlist;
		this.attrs = attrs;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ruleid", unique = true, nullable = false)
	public Integer getRuleid() {
		return this.ruleid;
	}

	public void setRuleid(Integer ruleid) {
		this.ruleid = ruleid;
	}

	@Column(name = "groupid", nullable = false)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "prefix", nullable = false, length = 64)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "timerec", nullable = false)
	public String getTimerec() {
		return this.timerec;
	}

	public void setTimerec(String timerec) {
		this.timerec = timerec;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

	@Column(name = "routeid", nullable = false)
	public String getRouteid() {
		return this.routeid;
	}

	public void setRouteid(String routeid) {
		this.routeid = routeid;
	}

	@Column(name = "gwlist", nullable = false)
	public String getGwlist() {
		return this.gwlist;
	}

	public void setGwlist(String gwlist) {
		this.gwlist = gwlist;
	}

	@Column(name = "attrs")
	public String getAttrs() {
		return this.attrs;
	}

	public void setAttrs(String attrs) {
		this.attrs = attrs;
	}

	@Column(name = "description", nullable = false, length = 128)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
