package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Globalblacklist generated by hbm2java
 */
@Entity
@Table(name = "globalblacklist", catalog = "phoenixdb")
public class Globalblacklist implements java.io.Serializable {

	private Integer id;
	private String prefix;
	private boolean whitelist;
	private String description;

	public Globalblacklist() {
	}

	public Globalblacklist(String prefix, boolean whitelist) {
		this.prefix = prefix;
		this.whitelist = whitelist;
	}

	public Globalblacklist(String prefix, boolean whitelist, String description) {
		this.prefix = prefix;
		this.whitelist = whitelist;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "prefix", nullable = false, length = 64)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "whitelist", nullable = false)
	public boolean isWhitelist() {
		return this.whitelist;
	}

	public void setWhitelist(boolean whitelist) {
		this.whitelist = whitelist;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
