package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Gw generated by hbm2java
 */
@Entity
@Table(name = "gw", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = "gw_name"))
public class Gw implements java.io.Serializable {

	private Integer id;
	private String gwName;
	private int grpId;
	private String ipAddr;
	private Short port;
	private Byte uriScheme;
	private Byte transport;
	private Byte strip;
	private String tag;
	private int flags;

	public Gw() {
	}

	public Gw(String gwName, int grpId, String ipAddr, int flags) {
		this.gwName = gwName;
		this.grpId = grpId;
		this.ipAddr = ipAddr;
		this.flags = flags;
	}

	public Gw(String gwName, int grpId, String ipAddr, Short port,
			Byte uriScheme, Byte transport, Byte strip, String tag, int flags) {
		this.gwName = gwName;
		this.grpId = grpId;
		this.ipAddr = ipAddr;
		this.port = port;
		this.uriScheme = uriScheme;
		this.transport = transport;
		this.strip = strip;
		this.tag = tag;
		this.flags = flags;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "gw_name", unique = true, nullable = false, length = 128)
	public String getGwName() {
		return this.gwName;
	}

	public void setGwName(String gwName) {
		this.gwName = gwName;
	}

	@Column(name = "grp_id", nullable = false)
	public int getGrpId() {
		return this.grpId;
	}

	public void setGrpId(int grpId) {
		this.grpId = grpId;
	}

	@Column(name = "ip_addr", nullable = false, length = 15)
	public String getIpAddr() {
		return this.ipAddr;
	}

	public void setIpAddr(String ipAddr) {
		this.ipAddr = ipAddr;
	}

	@Column(name = "port")
	public Short getPort() {
		return this.port;
	}

	public void setPort(Short port) {
		this.port = port;
	}

	@Column(name = "uri_scheme")
	public Byte getUriScheme() {
		return this.uriScheme;
	}

	public void setUriScheme(Byte uriScheme) {
		this.uriScheme = uriScheme;
	}

	@Column(name = "transport")
	public Byte getTransport() {
		return this.transport;
	}

	public void setTransport(Byte transport) {
		this.transport = transport;
	}

	@Column(name = "strip")
	public Byte getStrip() {
		return this.strip;
	}

	public void setStrip(Byte strip) {
		this.strip = strip;
	}

	@Column(name = "tag", length = 16)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

}
