package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ImcMembers generated by hbm2java
 */
@Entity
@Table(name = "imc_members", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"username", "domain", "room" }))
public class ImcMembers implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String room;
	private int flag;

	public ImcMembers() {
	}

	public ImcMembers(String username, String domain, String room, int flag) {
		this.username = username;
		this.domain = domain;
		this.room = room;
		this.flag = flag;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "room", nullable = false, length = 64)
	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	@Column(name = "flag", nullable = false)
	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

}
