package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Lcr generated by hbm2java
 */
@Entity
@Table(name = "lcr")
public class Lcr implements java.io.Serializable {

	private Integer id;
	private String prefix;
	private String fromUri;
	private int grpId;
	private int priority;

	public Lcr() {
	}

	public Lcr(int grpId, int priority) {
		this.grpId = grpId;
		this.priority = priority;
	}

	public Lcr(String prefix, String fromUri, int grpId, int priority) {
		this.prefix = prefix;
		this.fromUri = fromUri;
		this.grpId = grpId;
		this.priority = priority;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "prefix", length = 16)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "from_uri", length = 64)
	public String getFromUri() {
		return this.fromUri;
	}

	public void setFromUri(String fromUri) {
		this.fromUri = fromUri;
	}

	@Column(name = "grp_id", nullable = false)
	public int getGrpId() {
		return this.grpId;
	}

	public void setGrpId(int grpId) {
		this.grpId = grpId;
	}

	@Column(name = "priority", nullable = false)
	public int getPriority() {
		return this.priority;
	}

	public void setPriority(int priority) {
		this.priority = priority;
	}

}
