package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NhSockets generated by hbm2java
 */
@Entity
@Table(name = "nh_sockets")
public class NhSockets implements java.io.Serializable {

	private Integer id;
	private String rtpproxySock;
	private int setId;

	public NhSockets() {
	}

	public NhSockets(String rtpproxySock, int setId) {
		this.rtpproxySock = rtpproxySock;
		this.setId = setId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rtpproxy_sock", nullable = false, length = 65535)
	public String getRtpproxySock() {
		return this.rtpproxySock;
	}

	public void setRtpproxySock(String rtpproxySock) {
		this.rtpproxySock = rtpproxySock;
	}

	@Column(name = "set_id", nullable = false)
	public int getSetId() {
		return this.setId;
	}

	public void setSetId(int setId) {
		this.setId = setId;
	}

}
