package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pdt generated by hbm2java
 */
@Entity
@Table(name = "pdt", uniqueConstraints = @UniqueConstraint(columnNames = {
		"sdomain", "prefix" }))
public class Pdt implements java.io.Serializable {

	private Integer id;
	private String sdomain;
	private String prefix;
	private String domain;

	public Pdt() {
	}

	public Pdt(String sdomain, String prefix, String domain) {
		this.sdomain = sdomain;
		this.prefix = prefix;
		this.domain = domain;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "sdomain", nullable = false, length = 128)
	public String getSdomain() {
		return this.sdomain;
	}

	public void setSdomain(String sdomain) {
		this.sdomain = sdomain;
	}

	@Column(name = "prefix", nullable = false, length = 32)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "domain", nullable = false, length = 128)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

}
