package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Presentity generated by hbm2java
 */
@Entity
@Table(name = "presentity", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"username", "domain", "event", "etag" }))
public class Presentity implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String event;
	private String etag;
	private int expires;
	private int receivedTime;
	private byte[] body;
	private byte[] extraHdrs;
	private String sender;

	public Presentity() {
	}

	public Presentity(String username, String domain, String event,
			String etag, int expires, int receivedTime, byte[] body,
			byte[] extraHdrs, String sender) {
		this.username = username;
		this.domain = domain;
		this.event = event;
		this.etag = etag;
		this.expires = expires;
		this.receivedTime = receivedTime;
		this.body = body;
		this.extraHdrs = extraHdrs;
		this.sender = sender;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "event", nullable = false, length = 64)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "etag", nullable = false, length = 64)
	public String getEtag() {
		return this.etag;
	}

	public void setEtag(String etag) {
		this.etag = etag;
	}

	@Column(name = "expires", nullable = false)
	public int getExpires() {
		return this.expires;
	}

	public void setExpires(int expires) {
		this.expires = expires;
	}

	@Column(name = "received_time", nullable = false)
	public int getReceivedTime() {
		return this.receivedTime;
	}

	public void setReceivedTime(int receivedTime) {
		this.receivedTime = receivedTime;
	}

	@Column(name = "body", nullable = false)
	public byte[] getBody() {
		return this.body;
	}

	public void setBody(byte[] body) {
		this.body = body;
	}

	@Column(name = "extra_hdrs", nullable = false)
	public byte[] getExtraHdrs() {
		return this.extraHdrs;
	}

	public void setExtraHdrs(byte[] extraHdrs) {
		this.extraHdrs = extraHdrs;
	}

	@Column(name = "sender", nullable = false, length = 128)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

}
