package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RlsPresentity generated by hbm2java
 */
@Entity
@Table(name = "rls_presentity", catalog = "phoenixdb", uniqueConstraints = @UniqueConstraint(columnNames = {
		"rlsubs_did", "resource_uri" }))
public class RlsPresentity implements java.io.Serializable {

	private Integer id;
	private String rlsubsDid;
	private String resourceUri;
	private String contentType;
	private byte[] presenceState;
	private int expires;
	private int updated;
	private int authState;
	private String reason;

	public RlsPresentity() {
	}

	public RlsPresentity(String rlsubsDid, String resourceUri,
			String contentType, byte[] presenceState, int expires, int updated,
			int authState, String reason) {
		this.rlsubsDid = rlsubsDid;
		this.resourceUri = resourceUri;
		this.contentType = contentType;
		this.presenceState = presenceState;
		this.expires = expires;
		this.updated = updated;
		this.authState = authState;
		this.reason = reason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "rlsubs_did", nullable = false)
	public String getRlsubsDid() {
		return this.rlsubsDid;
	}

	public void setRlsubsDid(String rlsubsDid) {
		this.rlsubsDid = rlsubsDid;
	}

	@Column(name = "resource_uri", nullable = false, length = 128)
	public String getResourceUri() {
		return this.resourceUri;
	}

	public void setResourceUri(String resourceUri) {
		this.resourceUri = resourceUri;
	}

	@Column(name = "content_type", nullable = false)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "presence_state", nullable = false)
	public byte[] getPresenceState() {
		return this.presenceState;
	}

	public void setPresenceState(byte[] presenceState) {
		this.presenceState = presenceState;
	}

	@Column(name = "expires", nullable = false)
	public int getExpires() {
		return this.expires;
	}

	public void setExpires(int expires) {
		this.expires = expires;
	}

	@Column(name = "updated", nullable = false)
	public int getUpdated() {
		return this.updated;
	}

	public void setUpdated(int updated) {
		this.updated = updated;
	}

	@Column(name = "auth_state", nullable = false)
	public int getAuthState() {
		return this.authState;
	}

	public void setAuthState(int authState) {
		this.authState = authState;
	}

	@Column(name = "reason", nullable = false, length = 64)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
