package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * RlsWatchers generated by hbm2java
 */
@Entity
@Table(name = "rls_watchers", uniqueConstraints = @UniqueConstraint(columnNames = {
		"presentity_uri", "callid", "to_tag", "from_tag" }))
public class RlsWatchers implements java.io.Serializable {

	private Integer id;
	private int version;
	private String presentityUri;
	private String toUser;
	private String toDomain;
	private String watcherUsername;
	private String watcherDomain;
	private String event;
	private String eventId;
	private String toTag;
	private String fromTag;
	private String callid;
	private int localCseq;
	private int remoteCseq;
	private String contact;
	private String recordRoute;
	private int expires;
	private int status;
	private String reason;
	private String socketInfo;
	private String localContact;

	public RlsWatchers() {
	}

	public RlsWatchers(String presentityUri, String toUser, String toDomain,
			String watcherUsername, String watcherDomain, String event,
			String toTag, String fromTag, String callid, int localCseq,
			int remoteCseq, String contact, int expires, int status,
			String reason, String socketInfo, String localContact) {
		this.presentityUri = presentityUri;
		this.toUser = toUser;
		this.toDomain = toDomain;
		this.watcherUsername = watcherUsername;
		this.watcherDomain = watcherDomain;
		this.event = event;
		this.toTag = toTag;
		this.fromTag = fromTag;
		this.callid = callid;
		this.localCseq = localCseq;
		this.remoteCseq = remoteCseq;
		this.contact = contact;
		this.expires = expires;
		this.status = status;
		this.reason = reason;
		this.socketInfo = socketInfo;
		this.localContact = localContact;
	}

	public RlsWatchers(String presentityUri, String toUser, String toDomain,
			String watcherUsername, String watcherDomain, String event,
			String eventId, String toTag, String fromTag, String callid,
			int localCseq, int remoteCseq, String contact, String recordRoute,
			int expires, int status, String reason, String socketInfo,
			String localContact) {
		this.presentityUri = presentityUri;
		this.toUser = toUser;
		this.toDomain = toDomain;
		this.watcherUsername = watcherUsername;
		this.watcherDomain = watcherDomain;
		this.event = event;
		this.eventId = eventId;
		this.toTag = toTag;
		this.fromTag = fromTag;
		this.callid = callid;
		this.localCseq = localCseq;
		this.remoteCseq = remoteCseq;
		this.contact = contact;
		this.recordRoute = recordRoute;
		this.expires = expires;
		this.status = status;
		this.reason = reason;
		this.socketInfo = socketInfo;
		this.localContact = localContact;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "presentity_uri", nullable = false, length = 128)
	public String getPresentityUri() {
		return this.presentityUri;
	}

	public void setPresentityUri(String presentityUri) {
		this.presentityUri = presentityUri;
	}

	@Column(name = "to_user", nullable = false, length = 64)
	public String getToUser() {
		return this.toUser;
	}

	public void setToUser(String toUser) {
		this.toUser = toUser;
	}

	@Column(name = "to_domain", nullable = false, length = 64)
	public String getToDomain() {
		return this.toDomain;
	}

	public void setToDomain(String toDomain) {
		this.toDomain = toDomain;
	}

	@Column(name = "watcher_username", nullable = false, length = 64)
	public String getWatcherUsername() {
		return this.watcherUsername;
	}

	public void setWatcherUsername(String watcherUsername) {
		this.watcherUsername = watcherUsername;
	}

	@Column(name = "watcher_domain", nullable = false, length = 64)
	public String getWatcherDomain() {
		return this.watcherDomain;
	}

	public void setWatcherDomain(String watcherDomain) {
		this.watcherDomain = watcherDomain;
	}

	@Column(name = "event", nullable = false, length = 64)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "event_id", length = 64)
	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	@Column(name = "to_tag", nullable = false, length = 64)
	public String getToTag() {
		return this.toTag;
	}

	public void setToTag(String toTag) {
		this.toTag = toTag;
	}

	@Column(name = "from_tag", nullable = false, length = 64)
	public String getFromTag() {
		return this.fromTag;
	}

	public void setFromTag(String fromTag) {
		this.fromTag = fromTag;
	}

	@Column(name = "callid", nullable = false, length = 64)
	public String getCallid() {
		return this.callid;
	}

	public void setCallid(String callid) {
		this.callid = callid;
	}

	@Column(name = "local_cseq", nullable = false)
	public int getLocalCseq() {
		return this.localCseq;
	}

	public void setLocalCseq(int localCseq) {
		this.localCseq = localCseq;
	}

	@Column(name = "remote_cseq", nullable = false)
	public int getRemoteCseq() {
		return this.remoteCseq;
	}

	public void setRemoteCseq(int remoteCseq) {
		this.remoteCseq = remoteCseq;
	}

	@Column(name = "contact", nullable = false, length = 64)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "record_route", length = 65535)
	public String getRecordRoute() {
		return this.recordRoute;
	}

	public void setRecordRoute(String recordRoute) {
		this.recordRoute = recordRoute;
	}

	@Column(name = "expires", nullable = false)
	public int getExpires() {
		return this.expires;
	}

	public void setExpires(int expires) {
		this.expires = expires;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "reason", nullable = false, length = 64)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "socket_info", nullable = false, length = 64)
	public String getSocketInfo() {
		return this.socketInfo;
	}

	public void setSocketInfo(String socketInfo) {
		this.socketInfo = socketInfo;
	}

	@Column(name = "local_contact", nullable = false, length = 128)
	public String getLocalContact() {
		return this.localContact;
	}

	public void setLocalContact(String localContact) {
		this.localContact = localContact;
	}

}
