package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Silo generated by hbm2java
 */
@Entity
@Table(name = "silo")
public class Silo implements java.io.Serializable {

	private Integer id;
	private String srcAddr;
	private String dstAddr;
	private String username;
	private String domain;
	private int incTime;
	private int expTime;
	private int sndTime;
	private String ctype;
	private byte[] body;

	public Silo() {
	}

	public Silo(String srcAddr, String dstAddr, String username, String domain,
			int incTime, int expTime, int sndTime, String ctype, byte[] body) {
		this.srcAddr = srcAddr;
		this.dstAddr = dstAddr;
		this.username = username;
		this.domain = domain;
		this.incTime = incTime;
		this.expTime = expTime;
		this.sndTime = sndTime;
		this.ctype = ctype;
		this.body = body;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "src_addr", nullable = false, length = 128)
	public String getSrcAddr() {
		return this.srcAddr;
	}

	public void setSrcAddr(String srcAddr) {
		this.srcAddr = srcAddr;
	}

	@Column(name = "dst_addr", nullable = false, length = 128)
	public String getDstAddr() {
		return this.dstAddr;
	}

	public void setDstAddr(String dstAddr) {
		this.dstAddr = dstAddr;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "inc_time", nullable = false)
	public int getIncTime() {
		return this.incTime;
	}

	public void setIncTime(int incTime) {
		this.incTime = incTime;
	}

	@Column(name = "exp_time", nullable = false)
	public int getExpTime() {
		return this.expTime;
	}

	public void setExpTime(int expTime) {
		this.expTime = expTime;
	}

	@Column(name = "snd_time", nullable = false)
	public int getSndTime() {
		return this.sndTime;
	}

	public void setSndTime(int sndTime) {
		this.sndTime = sndTime;
	}

	@Column(name = "ctype", nullable = false, length = 32)
	public String getCtype() {
		return this.ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	@Column(name = "body", nullable = false)
	public byte[] getBody() {
		return this.body;
	}

	public void setBody(byte[] body) {
		this.body = body;
	}

}
