package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Subscriber generated by hbm2java
 */
@Entity
@Table(name = "subscriber", uniqueConstraints = @UniqueConstraint(columnNames = {
		"username", "domain" }))
public class Subscriber implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String password;
	private String emailAddress;
	private String ha1;
	private String ha1b;
	private String rpid;
	private boolean isAdmin;
	private Integer primaryGroup;
        
        // can user sign new certificate?
        private Boolean canSignNewCert=false;

	public Subscriber() {
	}

	public Subscriber(String username, String domain, String password,
			String emailAddress, String ha1, String ha1b, boolean isAdmin) {
		this.username = username;
		this.domain = domain;
		this.password = password;
		this.emailAddress = emailAddress;
		this.ha1 = ha1;
		this.ha1b = ha1b;
		this.isAdmin = isAdmin;
	}

	public Subscriber(String username, String domain, String password,
			String emailAddress, String ha1, String ha1b, String rpid,
			boolean isAdmin, Integer primaryGroup) {
		this.username = username;
		this.domain = domain;
		this.password = password;
		this.emailAddress = emailAddress;
		this.ha1 = ha1;
		this.ha1b = ha1b;
		this.rpid = rpid;
		this.isAdmin = isAdmin;
		this.primaryGroup = primaryGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "password", nullable = false, length = 25)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email_address", nullable = false, length = 64)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "ha1", nullable = false, length = 64)
	public String getHa1() {
		return this.ha1;
	}

	public void setHa1(String ha1) {
		this.ha1 = ha1;
	}

	@Column(name = "ha1b", nullable = false, length = 64)
	public String getHa1b() {
		return this.ha1b;
	}

	public void setHa1b(String ha1b) {
		this.ha1b = ha1b;
	}

	@Column(name = "rpid", length = 64)
	public String getRpid() {
		return this.rpid;
	}

	public void setRpid(String rpid) {
		this.rpid = rpid;
	}

	@Column(name = "isAdmin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

	@Column(name = "primaryGroup")
	public Integer getPrimaryGroup() {
		return this.primaryGroup;
	}

	public void setPrimaryGroup(Integer primaryGroup) {
		this.primaryGroup = primaryGroup;
	}

        /**
        *
        * @return
        */
        @Column(name = "canSignNewCert", nullable = false, columnDefinition = "TINYINT(1)")
        public Boolean isCanSignNewCert() {
            return canSignNewCert;
        }

        public void setCanSignNewCert(Boolean canSignNewCert) {
            this.canSignNewCert = canSignNewCert;
        }
}
