package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Userblacklist generated by hbm2java
 */
@Entity
@Table(name = "userblacklist", catalog = "phoenixdb")
public class Userblacklist implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private String prefix;
	private boolean whitelist;

	public Userblacklist() {
	}

	public Userblacklist(String username, String domain, String prefix,
			boolean whitelist) {
		this.username = username;
		this.domain = domain;
		this.prefix = prefix;
		this.whitelist = whitelist;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "prefix", nullable = false, length = 64)
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "whitelist", nullable = false)
	public boolean isWhitelist() {
		return this.whitelist;
	}

	public void setWhitelist(boolean whitelist) {
		this.whitelist = whitelist;
	}

}
