package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VersionId generated by hbm2java
 */
@Embeddable
public class VersionId implements java.io.Serializable {

	private String tableName;
	private int tableVersion;

	public VersionId() {
	}

	public VersionId(String tableName, int tableVersion) {
		this.tableName = tableName;
		this.tableVersion = tableVersion;
	}

	@Column(name = "table_name", unique = true, nullable = false, length = 32)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "table_version", nullable = false)
	public int getTableVersion() {
		return this.tableVersion;
	}

	public void setTableVersion(int tableVersion) {
		this.tableVersion = tableVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VersionId))
			return false;
		VersionId castOther = (VersionId) other;

		return ((this.getTableName() == castOther.getTableName()) || (this
				.getTableName() != null && castOther.getTableName() != null && this
				.getTableName().equals(castOther.getTableName())))
				&& (this.getTableVersion() == castOther.getTableVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTableName() == null ? 0 : this.getTableName().hashCode());
		result = 37 * result + this.getTableVersion();
		return result;
	}

}
