package com.phoenix.db.opensips;

// Generated Dec 2, 2012 7:18:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Xcap generated by hbm2java
 */
@Entity
@Table(name = "xcap", uniqueConstraints = @UniqueConstraint(columnNames = {
		"username", "domain", "doc_type", "doc_uri" }))
public class Xcap implements java.io.Serializable {

	private Integer id;
	private String username;
	private String domain;
	private byte[] doc;
	private int docType;
	private String etag;
	private int source;
	private String docUri;
	private int port;

	public Xcap() {
	}

	public Xcap(String username, String domain, byte[] doc, int docType,
			String etag, int source, String docUri, int port) {
		this.username = username;
		this.domain = domain;
		this.doc = doc;
		this.docType = docType;
		this.etag = etag;
		this.source = source;
		this.docUri = docUri;
		this.port = port;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "domain", nullable = false, length = 64)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "doc", nullable = false)
	public byte[] getDoc() {
		return this.doc;
	}

	public void setDoc(byte[] doc) {
		this.doc = doc;
	}

	@Column(name = "doc_type", nullable = false)
	public int getDocType() {
		return this.docType;
	}

	public void setDocType(int docType) {
		this.docType = docType;
	}

	@Column(name = "etag", nullable = false, length = 64)
	public String getEtag() {
		return this.etag;
	}

	public void setEtag(String etag) {
		this.etag = etag;
	}

	@Column(name = "source", nullable = false)
	public int getSource() {
		return this.source;
	}

	public void setSource(int source) {
		this.source = source;
	}

	@Column(name = "doc_uri", nullable = false, length = 128)
	public String getDocUri() {
		return this.docUri;
	}

	public void setDocUri(String docUri) {
		this.docUri = docUri;
	}

	@Column(name = "port", nullable = false)
	public int getPort() {
		return this.port;
	}

	public void setPort(int port) {
		this.port = port;
	}

}
